#!/bin/sh

/bin/mount -t proc proc /proc
/bin/mount -t sysfs proc /sys

/bin/mount -n -t tmpfs none /dev
/bin/mknod -m 622 /dev/console c 5 1
/bin/mknod -m 666 /dev/null c 1 3
/bin/mknod -m 666 /dev/zero c 1 5
/bin/mknod -m 666 /dev/ptmx c 5 2
/bin/mknod -m 666 /dev/tty c 5 0
/bin/mknod -m 444 /dev/random c 1 8
/bin/mknod -m 444 /dev/urandom c 1 9
/bin/mkdir /dev/pts
/bin/mount -t devpts none /dev/pts
/sbin/mdev -s

echo 5 > /sys/class/gpio/export
echo "rising" > /sys/class/gpio/gpio5/edge
echo 22 > /sys/class/gpio/export
echo "rising" > /sys/class/gpio/gpio22/edge
echo 23 > /sys/class/gpio/export
echo "rising" > /sys/class/gpio/gpio23/edge
echo 17 > /sys/class/gpio/export
echo "rising" > /sys/class/gpio/gpio17/edge

# script -f /dev/tty0
exec setsid /bin/sh -c 'exec /bin/sh </dev/ttyS0 >/dev/ttyS0 2>&1'
